# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [4]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

3. Create a vector with values ranging from 10 to 49

In [7]:
x=np.arange(10,50)

4. Find the shape of previous array in question 3

In [9]:
x.shape

(40,)

5. Print the type of the previous array in question 3

In [10]:
x.dtype

dtype('int64')

6. Print the numpy version and the configuration


In [11]:
print(np.__version__)
print(np.show_config())

1.19.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


7. Print the dimension of the array in question 3


In [12]:
x.ndim

1

8. Create a boolean array with all the True values

In [16]:
np.ones((3,3),dtype=bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

9. Create a two dimensional array




In [20]:
np.array([[1,2,3,4],[5,6,7,8]])


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

10. Create a three dimensional array



In [21]:
np.array([[1,2,3],[5,6,7],[4,8,9]])


array([[1, 2, 3],
       [5, 6, 7],
       [4, 8, 9]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [28]:
x=np.array([1,2,3,4])
x=x[::-1]
print(x)

[4 3 2 1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [30]:
array=np.zeros(10,)
array[5]=1

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [41]:
np.identity(3)
    

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [45]:
arr = np.array([1, 2, 3, 4, 5],dtype=np.float64)

dtype('float64')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [46]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [51]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
comparison = arr1 == arr2
comparison.all()

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [54]:
arr=np.arange(0,10)
arr[1::2]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

18. Replace all odd numbers to -1 from previous array

In [56]:
arr[1::2]=-1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [57]:
arr = np.arange(10)
arr[5:9]=12

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [65]:
x=np.ones((5,5))
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [69]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[1][1]=12

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [73]:
arr2d[0]=64
arr2d

array([[64, 64, 64],
       [ 4, 12,  6],
       [ 7,  8,  9]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [79]:
arr=np.arange(10)
arr=arr.reshape((2,5))
arr[0]

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [80]:
arr[1][1]

6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [81]:
arr[0:2,2]

array([2, 7])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [89]:
x=np.random.randn(10,10)
x.max()
x.min()

-2.6058832992434176

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [91]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)



array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [92]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7]),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [6]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names!="Will"]

array([[-0.5536433 , -0.22231431,  0.39747835, -0.0826252 ],
       [-0.47391867,  0.57272317, -1.15465704,  0.93820213],
       [ 1.4424043 ,  2.61567391,  0.44363209, -0.20658752],
       [-0.18086825,  1.51479937, -1.00652861,  0.41759001],
       [ 0.40914925, -0.18259357, -0.98925582, -2.26835923]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [9]:
print(data)
data[(names!="Will") & (names!="Joe")]

[[-0.5536433  -0.22231431  0.39747835 -0.0826252 ]
 [-0.47391867  0.57272317 -1.15465704  0.93820213]
 [-1.12827692 -1.3853517  -0.97202075 -0.94071361]
 [ 1.4424043   2.61567391  0.44363209 -0.20658752]
 [-0.5582225  -0.18277151  1.57231476 -1.15955661]
 [-0.18086825  1.51479937 -1.00652861  0.41759001]
 [ 0.40914925 -0.18259357 -0.98925582 -2.26835923]]


array([[-0.5536433 , -0.22231431,  0.39747835, -0.0826252 ],
       [ 1.4424043 ,  2.61567391,  0.44363209, -0.20658752]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [12]:
np.reshape(np.arange(1,16),(5,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [13]:
np.reshape(np.arange(1,17),(2,2,4))

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [ ]:
arr.swapaxis(1,2)

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [15]:
arr=np.array([0.01,4,5,6,7,2,0.001,2,3,4])
np.where(arr<0.5,0,np.sqrt(arr))

array([0.        , 2.        , 2.23606798, 2.44948974, 2.64575131,
       1.41421356, 0.        , 1.41421356, 1.73205081, 2.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [17]:
arr1=np.random.randn(12)
arr2=np.random.randn(12)
np.maximum(arr1,arr2)

array([ 0.73688731, -0.21361655,  1.13236928, -0.57153052,  1.28863511,
        1.01218043, -0.27105343,  2.20158475, -0.31068645,  0.1704308 ,
        0.51077095,  0.8650832 ])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [27]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
sorted(set(np.unique(names)))

['Bob', 'Joe', 'Will']

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [30]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [34]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[2]=newColumn
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [10, 10, 10]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [35]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [37]:
(np.random.randn(20)).cumsum()

array([ 0.92647492,  1.24290026,  1.8063717 ,  1.34309632,  1.82181376,
        0.97706814,  1.51375767,  1.2410829 ,  0.70827601,  0.90334135,
        1.68124892,  1.37464781, -0.06144448,  0.81899142, -0.66379073,
       -1.53906593, -2.82443271, -1.98898409, -2.16262819, -2.40472622])