# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
import numpy as np
np.reshape((np.arange(10)),(-1,5))


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [17]:
arr1=np.reshape((np.arange(10)),(-1,5))
arr2=np.ones((2,5))
np.vstack((arr1,arr2))

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [18]:
arr1=np.reshape((np.arange(10)),(-1,5))
arr2=np.ones((2,5))
np.hstack((arr1,arr2))

array([[0., 1., 2., 3., 4., 1., 1., 1., 1., 1.],
       [5., 6., 7., 8., 9., 1., 1., 1., 1., 1.]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [22]:
arr1=np.reshape((np.arange(10)),(-1,5))
arr1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [23]:
arr = np.arange(15).reshape((5, 3))
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [24]:
np.arange(15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [30]:
np.square(np.arange(25).reshape((5,5)))

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

## Question:8

### Create 5x6 an array and find the mean?

In [31]:
(np.arange(30).reshape(5,6)).mean()

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [32]:
(np.arange(30).reshape(5,6)).std()

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [35]:
np.median((np.arange(30).reshape(5,6)))

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [36]:
(np.arange(30).reshape(5,6)).transpose()

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [38]:
np.trace(np.arange(16).reshape(4,4))


30

## Question:13

### Find the determinant of the previous array in Q12?

In [46]:
mat=np.arange(4,20).reshape(4,4)
np.linalg.det(mat)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [54]:
x=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.percentile(x,5))
print(np.percentile(x,95))

1.4500000000000002
9.549999999999999


## Question:15

### How to find if a given array has any null values?

In [65]:
arr=np.array([0,1,2,3,4])
np.isnan(arr).any()

False